# Generated by Django 4.2.7 on 2024-01-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankrupt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankrupt', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposite', 'Deposite'), ('Withdrawal', 'Withdrawal'), ('Loan', 'Loan'), ('Loan Paid', 'Loan Paid')], max_length=100, null=True),
        ),
    ]
